"""empty message

Revision ID: e750731367cf
Revises: 1a3f05925b32
Create Date: 2020-02-18 06:45:01.740257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e750731367cf'
down_revision = '1a3f05925b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('sales_order_id_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'users', ['owner_id'], ['id'])
    op.drop_column('sales', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_order_id_fkey', 'sales', 'users', ['order_id'], ['id'])
    op.drop_column('sales', 'owner_id')
    # ### end Alembic commands ###
